; Generated by js-to-asm compiler

.include "os/v3/arithmetic/lib_math.asm"
.include "os/v3/drivers/lib_console.asm"
.include "os/v3/strings/lib_string.asm"


section .data
    x                db 0x00  ; var x
    y                db 0x00  ; var y
    result           db 0x00  ; var result
    MAX              equ 0x64  ; const
    arr              db 0x05, 0x0A, 0x0F, 0x14, 0x19  ; array[5]
    greeting         db "Hello World!", 0x00  ; string
    _str_0           db "[01] result = ", 0x00  ; string
    _log_buf         db 0x00, 0x00, 0x00, 0x00  ; int_to_str buffer
    i                db 0x00  ; var i
    _str_1           db "[02] after loop: ", 0x00  ; string
    j                db 0x00  ; var j
    _str_2           db "[04] final: ", 0x00  ; string


section .text
    call _main  ; entry point
    int3
    ret

_fn_add:
    ; load param a [SP+4]
    push cl
    push dl
    push el
    mov  cl, dl, esp  ; C:D = SP
    mov  el, 7
    call add_cd_e  ; C:D += 7
    ldi  al, cl, dl
    mov  bl, al
    pop  el
    pop  dl
    pop  cl
    mov  al, bl
    push al
    ; load param b [SP+3]
    push cl
    push dl
    push el
    mov  cl, dl, esp  ; C:D = SP
    mov  el, 6
    call add_cd_e  ; C:D += 6
    ldi  al, cl, dl
    mov  bl, al
    pop  el
    pop  dl
    pop  cl
    mov  al, bl
    mov  bl, al
    pop  al
    add  al, bl
    ret

_fn_max:
    ; load param a [SP+4]
    push cl
    push dl
    push el
    mov  cl, dl, esp  ; C:D = SP
    mov  el, 7
    call add_cd_e  ; C:D += 7
    ldi  al, cl, dl
    mov  bl, al
    pop  el
    pop  dl
    pop  cl
    mov  al, bl
    push al
    ; load param b [SP+3]
    push cl
    push dl
    push el
    mov  cl, dl, esp  ; C:D = SP
    mov  el, 6
    call add_cd_e  ; C:D += 6
    ldi  al, cl, dl
    mov  bl, al
    pop  el
    pop  dl
    pop  cl
    mov  al, bl
    mov  bl, al
    pop  al
    cmp  al, bl
    jg   .cmp_t_2
    mov  al, 0  ; false
    jmp  .cmp_e_3
  .cmp_t_2:
    mov  al, 1  ; true
  .cmp_e_3:
    cmp  al, 0
    jz   .else_0
    ; load param a [SP+4]
    push cl
    push dl
    push el
    mov  cl, dl, esp  ; C:D = SP
    mov  el, 7
    call add_cd_e  ; C:D += 7
    ldi  al, cl, dl
    mov  bl, al
    pop  el
    pop  dl
    pop  cl
    mov  al, bl
    ret
  .else_0:
    ; load param b [SP+3]
    push cl
    push dl
    push el
    mov  cl, dl, esp  ; C:D = SP
    mov  el, 6
    call add_cd_e  ; C:D += 6
    ldi  al, cl, dl
    mov  bl, al
    pop  el
    pop  dl
    pop  cl
    mov  al, bl
    ret
  .endif_1:
    ret

_fn_clamp:
    ; load param val [SP+3]
    push cl
    push dl
    push el
    mov  cl, dl, esp  ; C:D = SP
    mov  el, 6
    call add_cd_e  ; C:D += 6
    ldi  al, cl, dl
    mov  bl, al
    pop  el
    pop  dl
    pop  cl
    mov  al, bl
    push al
    mov  al, 0x64  ; MAX
    mov  bl, al
    pop  al
    cmp  al, bl
    jg   .cmp_t_6
    mov  al, 0  ; false
    jmp  .cmp_e_7
  .cmp_t_6:
    mov  al, 1  ; true
  .cmp_e_7:
    cmp  al, 0
    jz   .tern_e_4
    mov  al, 0x64  ; MAX
    jmp  .tern_end_5
  .tern_e_4:
    ; load param val [SP+3]
    push cl
    push dl
    push el
    mov  cl, dl, esp  ; C:D = SP
    mov  el, 6
    call add_cd_e  ; C:D += 6
    ldi  al, cl, dl
    mov  bl, al
    pop  el
    pop  dl
    pop  cl
    mov  al, bl
  .tern_end_5:
    ret

_main:
    call init_device_console  ; init console I/O
    mov  al, 0x0A
    mov  [x], al  ; x
    mov  al, 0x14
    mov  [y], al  ; y
    mov  al, 0
    mov  [result], al  ; result
    mov  al, [x]  ; x
    push al  ; arg0
    mov  al, [y]  ; y
    push al  ; arg1
    call _fn_add  ; add()
    pop  bl  ; clean 2 args
    pop  bl
    mov  [result], al  ; result
    ; console.log
    push cl
    push dl
    lea  cl, dl, [_str_0]
    call console_print_string
    mov  al, [result]  ; result
    lea  cl, dl, [_log_buf]
    call int_to_str  ; AL → string
    lea  cl, dl, [_log_buf]
    call console_print_string
    mov  al, 0x0D
    call console_print_char  ; newline
    pop  dl
    pop  cl
    mov  al, 0
    mov  [i], al  ; i
  .while_8:
    mov  al, [i]  ; i
    cmp  al, 5
    jl   .cmp_t_10
    mov  al, 0  ; false
    jmp  .cmp_e_11
  .cmp_t_10:
    mov  al, 1  ; true
  .cmp_e_11:
    cmp  al, 0
    jz   .endw_9
    mov  al, [result]  ; result
    push al
    mov  al, [i]  ; i
    push cl
    push dl
    mov  el, al  ; E = index
    lea  cl, dl, [arr]
    call add_cd_e  ; C:D = &arr[i]
    ldi  al, cl, dl  ; arr[i]
    pop  dl
    pop  cl
    mov  bl, al
    pop  al
    add  al, bl
    mov  [result], al  ; result
    mov  al, [i]  ; i
    push al  ; save old value
    inc  al
    mov  [i], al  ; i
    pop  al  ; result = old value
    jmp  .while_8
  .endw_9:
    ; console.log
    push cl
    push dl
    lea  cl, dl, [_str_1]
    call console_print_string
    mov  al, [result]  ; result
    lea  cl, dl, [_log_buf]
    call int_to_str  ; AL → string
    lea  cl, dl, [_log_buf]
    call console_print_string
    mov  al, 0x0D
    call console_print_char  ; newline
    pop  dl
    pop  cl
    mov  al, [result]  ; result
    cmp  al, 0x1E
    jg   .cmp_t_14
    mov  al, 0  ; false
    jmp  .cmp_e_15
  .cmp_t_14:
    mov  al, 1  ; true
  .cmp_e_15:
    cmp  al, 0
    jz   .endif_13
    mov  al, [result]  ; result
    push al  ; arg0
    mov  al, 0x64  ; MAX
    push al  ; arg1
    call _fn_max  ; max()
    pop  bl  ; clean 2 args
    pop  bl
    mov  [result], al  ; result
  .endif_13:
    mov  al, [x]  ; x
    push al
    cmp  al, 0x0A
    jnz  .case_17
    mov  al, 1
    mov  [result], al  ; result
    pop  bl  ; clean switch value
    jmp  .endsw_16
  .case_17:
    pop  al
    push al
    cmp  al, 0x14
    jnz  .case_18
    mov  al, 2
    mov  [result], al  ; result
    pop  bl  ; clean switch value
    jmp  .endsw_16
  .case_18:
    mov  al, 0
    mov  [result], al  ; result
    pop  bl  ; clean switch value
    jmp  .endsw_16
    pop  bl  ; clean switch value (fallthrough)
  .endsw_16:
    mov  al, 0
    mov  [j], al  ; j
  .for_19:
    mov  al, [j]  ; j
    cmp  al, 3
    jl   .cmp_t_21
    mov  al, 0  ; false
    jmp  .cmp_e_22
  .cmp_t_21:
    mov  al, 1  ; true
  .cmp_e_22:
    cmp  al, 0
    jz   .endf_20
    ; arr[i] = expr
    mov  al, [j]  ; j
    push al  ; save index
    mov  al, [j]  ; j
    push al
    mov  al, 0x0A
    mov  bl, al
    pop  al
    call mul8  ; al = al * bl
    mov  fl, al  ; FL = value
    pop  el  ; EL = index
    push cl
    push dl
    lea  cl, dl, [arr]
    call add_cd_e  ; C:D = &arr[i]
    sti  cl, dl, fl  ; arr[i] = FL
    pop  dl
    pop  cl
    mov  al, [j]  ; j
    push al  ; save old value
    inc  al
    mov  [j], al  ; j
    pop  al  ; result = old value
    jmp  .for_19
  .endf_20:
  .do_23:
    mov  al, [result]  ; result
    dec  al
    mov  [result], al  ; result
    mov  al, [result]  ; result
    cmp  al, 0
    jg   .cmp_t_24
    mov  al, 0  ; false
    jmp  .cmp_e_25
  .cmp_t_24:
    mov  al, 1  ; true
  .cmp_e_25:
    cmp  al, 0
    jnz  .do_23
    ; console.log
    push cl
    push dl
    lea  cl, dl, [greeting]
    call console_print_string
    mov  al, 0x0D
    call console_print_char  ; newline
    pop  dl
    pop  cl
    ; console.log
    push cl
    push dl
    lea  cl, dl, [_str_2]
    call console_print_string
    mov  al, [result]  ; result
    lea  cl, dl, [_log_buf]
    call int_to_str  ; AL → string
    lea  cl, dl, [_log_buf]
    call console_print_string
    mov  al, 0x0D
    call console_print_char  ; newline
    pop  dl
    pop  cl
    ret
