; Generated by js-to-asm compiler

.include "os/v3/arithmetic/lib_math.asm"
.include "os/v3/drivers/lib_console.asm"
.include "os/v3/strings/lib_string.asm"


section .data
    i                db 0x00  ; var i
    result           db 0x00  ; var result
    _str_0           db "5 - ", 0x00  ; string
    _log_buf         db 0x00, 0x00, 0x00, 0x00  ; int_to_str buffer
    _str_1           db " = ", 0x00  ; string


section .text
    call _main  ; entry point
    int3
    ret

_main:
    call init_device_console  ; init console I/O
    mov  al, 0
    mov  [i], al  ; i
  .for_0:
    mov  al, [i]  ; i
    cmp  al, 0x0F
    jl   .cmp_t_2
    mov  al, 0  ; false
    jmp  .cmp_e_3
  .cmp_t_2:
    mov  al, 1  ; true
  .cmp_e_3:
    cmp  al, 0
    jz   .endf_1
    mov  al, 5
    push al
    mov  al, [i]  ; i
    mov  bl, al
    pop  al
    sub  al, bl
    mov  [result], al  ; result
    ; console.log
    push cl
    push dl
    lea  cl, dl, [_str_0]
    call console_print_string
    mov  al, [i]  ; i
    lea  cl, dl, [_log_buf]
    call int_to_str  ; AL → string
    lea  cl, dl, [_log_buf]
    call console_print_string
    lea  cl, dl, [_str_1]
    call console_print_string
    mov  al, [result]  ; result
    lea  cl, dl, [_log_buf]
    call int_to_str  ; AL → string
    lea  cl, dl, [_log_buf]
    call console_print_string
    mov  al, 0x0D
    call console_print_char  ; newline
    pop  dl
    pop  cl
    mov  al, [i]  ; i
    push al  ; save old value
    inc  al
    mov  [i], al  ; i
    pop  al  ; result = old value
    jmp  .for_0
  .endf_1:
    ret