; Generated by js-to-asm compiler

.include "os/v3/arithmetic/lib_math.asm"
.include "os/v3/drivers/lib_console.asm"
.include "os/v3/strings/lib_string.asm"


section .data
    greeting         db "Hello World !", 0x00  ; string
    _str_0           db "
", 0x00  ; string
    _log_buf         db 0x00, 0x00, 0x00, 0x00  ; int_to_str buffer


section .text
    call _main  ; entry point
    int3
    ret

_fn_hello:
    ; console.log
    push cl
    push dl
    lea  cl, dl, [greeting]
    call console_print_string
    lea  cl, dl, [_str_0]
    call console_print_string
    mov  al, 0x2A  ; const: 40 + 2
    lea  cl, dl, [_log_buf]
    call int_to_str  ; AL → string
    lea  cl, dl, [_log_buf]
    call console_print_string
    mov  al, 0x0D
    call console_print_char  ; newline
    pop  dl
    pop  cl
    ret

_main:
    call init_device_console  ; init console I/O
    ret