; Generated by js-to-asm compiler

.include "os/v3/arithmetic/lib_math.asm"
.include "os/v3/drivers/lib_console.asm"
.include "os/v3/strings/lib_string.asm"


section .data
    x                db 0x00  ; var x
    y                db 0x00  ; var y
    result           db 0x00  ; var result
    _str_0           db "result = ", 0x00  ; string
    _log_buf         db 0x00, 0x00, 0x00, 0x00  ; int_to_str buffer


section .text
    call _main  ; entry point
    int3
    ret

_fn_add:
    ; load param a [SP+4]
    push cl
    push dl
    push el
    mov  cl, dl, esp  ; C:D = SP
    mov  el, 7
    call add_cd_e  ; C:D += 7
    ldi  al, cl, dl
    mov  bl, al
    pop  el
    pop  dl
    pop  cl
    mov  al, bl
    push al
    ; load param b [SP+3]
    push cl
    push dl
    push el
    mov  cl, dl, esp  ; C:D = SP
    mov  el, 6
    call add_cd_e  ; C:D += 6
    ldi  al, cl, dl
    mov  bl, al
    pop  el
    pop  dl
    pop  cl
    mov  al, bl
    mov  bl, al
    pop  al
    add  al, bl
    ret

_main:
    call init_device_console  ; init console I/O
    mov  al, 0x0A
    mov  [x], al  ; x
    mov  al, 0x14
    mov  [y], al  ; y
    mov  al, 0
    mov  [result], al  ; result
    mov  al, [x]  ; x
    push al  ; arg0
    mov  al, [y]  ; y
    push al  ; arg1
    call _fn_add  ; add()
    pop  bl  ; clean 2 args
    pop  bl
    mov  [result], al  ; result
    ; console.log
    push cl
    push dl
    lea  cl, dl, [_str_0]
    call console_print_string
    mov  al, [result]  ; result
    lea  cl, dl, [_log_buf]
    call int_to_str  ; AL → string
    lea  cl, dl, [_log_buf]
    call console_print_string
    mov  al, 0x0D
    call console_print_char  ; newline
    pop  dl
    pop  cl
    ret